# SPDX-FileCopyrightText: Copyright (c) 2025 WanPhys Developers
# SPDX-License-Identifier: Apache-2.0

"""Curvature cross-validation tests against reference CUDA code.

Validates that Warp's ``calculate_curvature_from_grid`` produces **identical**
raw curvature values (including PLIC offset) as the reference CUDA C++
``calculate_curvature`` function, given the same phi and flag input.

The reference data is generated by ``export_curvature_golden.cu`` and stored
under ``golden_data/`` as:

* ``curvature_{scene}_phi.txt``  — N³ float32  (volume fraction)
* ``curvature_{scene}_flag.txt`` — N³ int32    (cell type)
* ``curvature_{scene}_values.txt`` — M float32 (curvature per TYPE_I cell)
* ``curvature_{scene}_indices.txt`` — M int32  (flat index of each TYPE_I cell)
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
import warp as wp

from wanphys._src.fluid.fluid_grid.home_fslbm import constants as C
from wanphys._src.fluid.fluid_grid.home_fslbm.kernels_fluid import (
    calculate_curvature_from_grid,
)

GOLDEN_DIR = Path(__file__).parent / "golden_data"


# ============================================================================
# Helpers
# ============================================================================


def _load_curvature_golden(scene_name: str) -> dict:
    """Load curvature golden data for a scene."""
    scene_dir = GOLDEN_DIR / "curvature" / scene_name

    return {
        "phi": np.loadtxt(scene_dir / "phi.txt", dtype=np.float32),
        "flag": np.loadtxt(scene_dir / "flag.txt", dtype=np.int32),
        "values": np.loadtxt(scene_dir / "values.txt", dtype=np.float32),
        "indices": np.loadtxt(scene_dir / "indices.txt", dtype=np.int32),
    }


def _make_direction_arrays(device):
    """Create D3Q27 cx, cy, cz, opposite arrays."""
    cx = wp.array(np.array(C.CX, dtype=np.int32), dtype=wp.int32, device=device)
    cy = wp.array(np.array(C.CY, dtype=np.int32), dtype=wp.int32, device=device)
    cz = wp.array(np.array(C.CZ, dtype=np.int32), dtype=wp.int32, device=device)
    opp = wp.array(np.array(C.OPPOSITE, dtype=np.int32), dtype=wp.int32, device=device)
    return cx, cy, cz, opp


@wp.kernel
def _curvature_at_indices_kernel(
    phi: wp.array3d(dtype=float),
    flag: wp.array3d(dtype=wp.uint8),
    cx: wp.array(dtype=wp.int32),
    cy: wp.array(dtype=wp.int32),
    cz: wp.array(dtype=wp.int32),
    opposite: wp.array(dtype=wp.int32),
    nx: int,
    ny: int,
    nz: int,
    indices: wp.array(dtype=wp.int32),    # [num_type_i] — flat indices
    curvatures: wp.array(dtype=float),     # [num_type_i] — output
):
    """Compute curvature at a set of pre-determined cell indices."""
    tid = wp.tid()
    if tid >= indices.shape[0]:
        return

    flat_idx = indices[tid]
    # Convert flat index → (i,j,k)
    # Layout: idx = k*ny*nx + j*nx + i
    kk = flat_idx // (ny * nx)
    rem = flat_idx % (ny * nx)
    jj = rem // nx
    ii = rem % nx

    # Use phi_center = phi[ii,jj,kk] (consistent with calculate_curvature_from_grid)
    phi_center = phi[ii, jj, kk]

    curv = calculate_curvature_from_grid(
        phi, flag, cx, cy, cz, opposite,
        ii, jj, kk, nx, ny, nz, 0, 0, 0, phi_center,
    )
    curvatures[tid] = curv


# ============================================================================
# Fixtures
# ============================================================================


@pytest.fixture(scope="module")
def device():
    try:
        return wp.get_device("cuda:0")
    except Exception:
        return wp.get_device("cpu")


# ============================================================================
# Test class
# ============================================================================


class TestCurvatureVsReference:
    """Cell-by-cell curvature comparison against reference CUDA output."""

    def _compare_scene(self, device, scene_name, N):
        """Load golden data, compute Warp curvatures, compare."""
        golden = _load_curvature_golden(scene_name)

        ref_phi = golden["phi"]       # shape (N*N*N,) flat
        ref_flag = golden["flag"]     # shape (N*N*N,) flat
        ref_values = golden["values"]  # shape (num_type_i,)
        ref_indices = golden["indices"]  # shape (num_type_i,)

        num_type_i = len(ref_values)
        assert num_type_i > 0, f"[{scene_name}] No TYPE_I cells in golden data"

        # Reshape to 3D, then transpose from ref (k,j,i) to Warp (i,j,k).
        # ascontiguousarray is REQUIRED: transpose returns a view with
        # non-standard strides; Warp may read the raw memory ignoring strides,
        # which would swap i/k axes and scramble the curvature computation.
        phi_3d = np.ascontiguousarray(ref_phi.reshape((N, N, N)).transpose(2, 1, 0))
        flag_3d = np.ascontiguousarray(ref_flag.reshape((N, N, N)).transpose(2, 1, 0)).astype(np.uint8)

        # Upload to GPU
        phi_wp = wp.array(phi_3d, dtype=float, device=device)
        flag_wp = wp.array(flag_3d, dtype=wp.uint8, device=device)

        # Verify GPU-side phi matches reference flat array
        phi_gpu = phi_wp.numpy()
        print(f"\n[{scene_name}] phi verification (first 5 TYPE_I):")
        for i in range(min(num_type_i, 5)):
            fidx = int(ref_indices[i])
            kk = fidx // (N * N)
            rem = fidx % (N * N)
            jj = rem // N
            ii = rem % N
            gpu_val = float(phi_gpu[ii, jj, kk])
            ref_val = float(ref_phi[fidx])
            ok = "OK" if abs(gpu_val - ref_val) < 1e-5 else "MISMATCH"
            print(f"  fidx={fidx:5d} (i={ii:2d},j={jj:2d},k={kk:2d}) gpu={gpu_val:+.6f} ref={ref_val:+.6f} {ok}")

        indices_wp = wp.array(ref_indices.astype(np.int32), dtype=wp.int32, device=device)
        curv_wp = wp.zeros(num_type_i, dtype=float, device=device)
        cx, cy, cz, opp = _make_direction_arrays(device)

        wp.launch(
            _curvature_at_indices_kernel,
            dim=num_type_i,
            inputs=[
                phi_wp, flag_wp,
                cx, cy, cz, opp,
                N, N, N,
                indices_wp, curv_wp,
            ],
            device=device,
        )

        warp_values = curv_wp.numpy()

        # Diagnostic: dump all curvature values side by side
        print(f"\n[{scene_name}] idx   ref_curv      warp_curv     diff")
        mismatch_count = 0
        for i in range(num_type_i):
            d = abs(warp_values[i] - ref_values[i])
            if d > 1e-6:
                print(f"  {int(ref_indices[i]):5d}  {ref_values[i]:+.6e}  {warp_values[i]:+.6e}  {d:.2e}")
                mismatch_count += 1
        print(f"  ({mismatch_count} mismatches shown out of {num_type_i} total)")

        # Compare: curvature values must match within strict tolerance
        abs_diff = np.abs(ref_values - warp_values)
        max_abs_err = float(np.max(abs_diff))
        mean_abs_err = float(np.mean(abs_diff))
        tol = 1e-6
        mismatches = int(np.sum(abs_diff > tol))
        print(f"[{scene_name}] {mismatches}/{num_type_i} differ, max_abs_err={max_abs_err:.2e}, mean_abs_err={mean_abs_err:.2e}")
        if mismatches > 0:
            worst_idx = int(np.argmax(abs_diff))
            raise AssertionError(
                f"[{scene_name}] {mismatches}/{num_type_i} curvatures differ "
                f"(tol={tol}): max_abs_err={max_abs_err:.2e}, "
                f"mean_abs_err={mean_abs_err:.2e}, "
                f"worst: idx={ref_indices[worst_idx]} "
                f"ref={ref_values[worst_idx]:.6e} warp={warp_values[worst_idx]:.6e}"
            )

    # ------------------------------------------------------------------
    # Tests
    # ------------------------------------------------------------------

    def test_sphere_r4_16(self, device):
        """R=4 sphere on 16^3 grid."""
        self._compare_scene(device, "sphere_r4_16", 16)

    def test_sphere_r8_32(self, device):
        """R=8 sphere on 32^3 grid."""
        self._compare_scene(device, "sphere_r8_32", 32)

    def test_plane_32(self, device):
        """Flat plane at z=16 on 32^3 grid."""
        self._compare_scene(device, "plane_32", 32)

    def test_cylinder_r6_32(self, device):
        """R=6 cylinder on 32^3 grid."""
        self._compare_scene(device, "cylinder_r6_32", 32)