# SPDX-FileCopyrightText: Copyright (c) 2025 WanPhys Developers
# SPDX-License-Identifier: Apache-2.0

"""Phase 2 golden-data regression tests for HOME-FSLBM free-surface.

Each test constructs a scene (droplet / flat interface / ellipsoid / …),
runs the full ``stream_collide_bvh + surface_1/2/3`` pipeline for a fixed
number of steps, and compares the final state against reference CUDA C++
output (golden ``.txt`` files).

The golden data is generated by the extended ``export_solver_golden.cpp``
in ``docs/papers/`` and stored as per-scene subdirectories under
``tests/golden_data/``.

.. note::

    **PLIC curvature offset**: the reference code and Warp share the same
    Monge-patch curvature formula with identical PLIC offset behaviour.
    The full-state regression tests below implicitly validate curvature
    (it feeds into the collision step via surface-tension Guo forcing),
    so matching f_mom_post / mass / phi / flag constitutes an end-to-end
    curvature verification.  Explicit cell-by-cell curvature comparison
    is in the companion ``test_regression_curvature.py``.
"""

from __future__ import annotations

import numpy as np
import pytest

from wanphys._src.fluid.fluid_grid.home_fslbm import constants as C
from wanphys._src.fluid.fluid_grid.home_fslbm.tests.conftest import (
    load_surface_golden,
)

# Reference GPU kernel hardcoded collision omega.
# Ref: mrLbmSolverGpu3D.cu — omega = 1 / (3 * 1e-4 + 0.5)
OMEGA_REF: float = 1.0 / (3.0 * 1e-4 + 0.5)  # ≈ 1.998800719568259


# ============================================================================
# Fixtures
# ============================================================================


@pytest.fixture(scope="module")
def _warp():
    import warp as wp
    return wp


# ============================================================================
# Helpers
# ============================================================================


def _setup_sphere_droplet(domain, N, R, cx=None, cy=None, cz=None):
    """Initialise flag/phi/mass for a sphere droplet.

    Uses phi = clamp((R - dist) / delta + 0.5, 0, 1) with delta = 1.5 dx.
    """
    import warp as wp

    if cx is None:
        cx = N / 2
    if cy is None:
        cy = N / 2
    if cz is None:
        cz = N / 2

    delta = 1.5
    phi_host = np.zeros((N, N, N), dtype=np.float32)
    flag_host = np.zeros((N, N, N), dtype=np.uint8)
    mass_host = np.zeros((N, N, N), dtype=np.float32)

    for k in range(N):
        for j in range(N):
            for i in range(N):
                dx = i - cx
                dy = j - cy
                dz = k - cz
                dist = np.sqrt(dx * dx + dy * dy + dz * dz)
                phi_raw = (R - dist) / delta + 0.5
                phi_val = max(0.0, min(1.0, phi_raw))
                phi_host[i, j, k] = phi_val
                if phi_val >= 1.0 - 1e-6:
                    flag_host[i, j, k] = C.CellFlag.TYPE_F
                    mass_host[i, j, k] = 1.0
                elif phi_val <= 1e-6:
                    flag_host[i, j, k] = C.CellFlag.TYPE_G
                    mass_host[i, j, k] = 0.0
                else:
                    flag_host[i, j, k] = C.CellFlag.TYPE_I
                    mass_host[i, j, k] = phi_val

    state = domain.state
    wp.copy(state.flag, wp.array(flag_host, dtype=wp.uint8, device=state.flag.device))
    wp.copy(state.phi, wp.array(phi_host, dtype=float, device=state.phi.device))
    wp.copy(state.mass, wp.array(mass_host, dtype=float, device=state.mass.device))
    _init_rest_state(domain, N)
    return flag_host, phi_host, mass_host


def _setup_flat_interface(domain, N, z_split=None):
    """Initialise a flat horizontal interface at z = z_split."""
    import warp as wp

    if z_split is None:
        z_split = N // 2

    delta = 1.5
    phi_host = np.zeros((N, N, N), dtype=np.float32)
    flag_host = np.zeros((N, N, N), dtype=np.uint8)
    mass_host = np.zeros((N, N, N), dtype=np.float32)

    for k in range(N):
        phi_raw = (z_split - k) / delta + 0.5
        phi_val = max(0.0, min(1.0, phi_raw))
        phi_host[:, :, k] = phi_val
        if phi_val >= 1.0 - 1e-6:
            flag_host[:, :, k] = C.CellFlag.TYPE_F
            mass_host[:, :, k] = 1.0
        elif phi_val <= 1e-6:
            flag_host[:, :, k] = C.CellFlag.TYPE_G
            mass_host[:, :, k] = 0.0
        else:
            flag_host[:, :, k] = C.CellFlag.TYPE_I
            mass_host[:, :, k] = phi_val

    state = domain.state
    wp.copy(state.flag, wp.array(flag_host, dtype=wp.uint8, device=state.flag.device))
    wp.copy(state.phi, wp.array(phi_host, dtype=float, device=state.phi.device))
    wp.copy(state.mass, wp.array(mass_host, dtype=float, device=state.mass.device))
    _init_rest_state(domain, N)
    return flag_host, phi_host, mass_host


def _setup_near_droplets(domain, N, R, center_dist):
    """Two spheres of radius R, centres separated by center_dist along x."""
    import warp as wp

    cx1 = N / 2 - center_dist / 2
    cx2 = N / 2 + center_dist / 2
    cy = N / 2
    cz = N / 2

    delta = 1.5
    phi_host = np.zeros((N, N, N), dtype=np.float32)
    flag_host = np.zeros((N, N, N), dtype=np.uint8)
    mass_host = np.zeros((N, N, N), dtype=np.float32)

    for k in range(N):
        for j in range(N):
            for i in range(N):
                d1 = np.sqrt((i - cx1) ** 2 + (j - cy) ** 2 + (k - cz) ** 2)
                d2 = np.sqrt((i - cx2) ** 2 + (j - cy) ** 2 + (k - cz) ** 2)
                phi1 = (R - d1) / delta + 0.5
                phi2 = (R - d2) / delta + 0.5
                phi_raw = max(phi1, phi2)
                phi_val = max(0.0, min(1.0, phi_raw))
                phi_host[i, j, k] = phi_val
                if phi_val >= 1.0 - 1e-6:
                    flag_host[i, j, k] = C.CellFlag.TYPE_F
                    mass_host[i, j, k] = 1.0
                elif phi_val <= 1e-6:
                    flag_host[i, j, k] = C.CellFlag.TYPE_G
                    mass_host[i, j, k] = 0.0
                else:
                    flag_host[i, j, k] = C.CellFlag.TYPE_I
                    mass_host[i, j, k] = phi_val

    state = domain.state
    wp.copy(state.flag, wp.array(flag_host, dtype=wp.uint8, device=state.flag.device))
    wp.copy(state.phi, wp.array(phi_host, dtype=float, device=state.phi.device))
    wp.copy(state.mass, wp.array(mass_host, dtype=float, device=state.mass.device))
    _init_rest_state(domain, N)
    return flag_host, phi_host, mass_host


def _setup_ellipsoid(domain, N, rx, ry, rz):
    """Ellipsoid (rx, ry, rz) at centre."""
    import warp as wp

    cx = N / 2
    cy = N / 2
    cz = N / 2
    delta = 1.5

    phi_host = np.zeros((N, N, N), dtype=np.float32)
    flag_host = np.zeros((N, N, N), dtype=np.uint8)
    mass_host = np.zeros((N, N, N), dtype=np.float32)

    for k in range(N):
        for j in range(N):
            for i in range(N):
                dx = (i - cx) / rx
                dy = (j - cy) / ry
                dz = (k - cz) / rz
                dist = np.sqrt(dx * dx + dy * dy + dz * dz)
                phi_raw = (1.0 - dist) * rx / delta + 0.5
                phi_val = max(0.0, min(1.0, phi_raw))
                phi_host[i, j, k] = phi_val
                if phi_val >= 1.0 - 1e-6:
                    flag_host[i, j, k] = C.CellFlag.TYPE_F
                    mass_host[i, j, k] = 1.0
                elif phi_val <= 1e-6:
                    flag_host[i, j, k] = C.CellFlag.TYPE_G
                    mass_host[i, j, k] = 0.0
                else:
                    flag_host[i, j, k] = C.CellFlag.TYPE_I
                    mass_host[i, j, k] = phi_val

    state = domain.state
    wp.copy(state.flag, wp.array(flag_host, dtype=wp.uint8, device=state.flag.device))
    wp.copy(state.phi, wp.array(phi_host, dtype=float, device=state.phi.device))
    wp.copy(state.mass, wp.array(mass_host, dtype=float, device=state.mass.device))
    _init_rest_state(domain, N)
    return flag_host, phi_host, mass_host


def _init_rest_state(domain, N):
    """Set f_mom/f_mom_post to equilibrium (rho=1, u=0).

    .. note::

        ``tag_matrix`` is initialised to -1 to match the reference code
        (``export_solver_golden.cpp``).  The reference GPU kernel hardcodes
        collision omega as ``1/(3*1e-4+0.5)`` ≈ 1.998, which is also the
        Warp base omega when no bubble-driven turbulence is active.
    """
    import warp as wp

    state = domain.state
    total = N * N * N

    # Equilibrium moments: rho=1, u=0, S_ab=0
    f_data = np.zeros(10 * total, dtype=np.float32)
    f_data[0 * total:1 * total] = 1.0  # rho
    # u = 0, S = 0 (already zero)

    f_mom_arr = wp.array(f_data, dtype=float, device=state.f_mom.device)
    wp.copy(state.f_mom, f_mom_arr)
    wp.copy(state.f_mom_post, f_mom_arr)

    # tag_matrix = -1  (match reference: export_solver_golden.cpp)
    tag_host = np.full((N, N, N), -1, dtype=np.int32)
    wp.copy(state.tag_matrix, wp.array(tag_host, dtype=wp.int32, device=state.tag_matrix.device))

    # massex = 0
    state.massex.zero_()

    # force = 0 (will be set by gravity in step)
    state.force_x.zero_()
    state.force_y.zero_()
    state.force_z.zero_()

    # delta_phi = 0
    state.delta_phi.zero_()


def _set_boundary_walls(state, N):
    """Set the 6 domain boundary faces to TYPE_S.

    Matches ``set_boundary_walls`` in ``export_solver_golden.cpp``.
    The golden generator applies TYPE_S to all 6 faces after scene setup;
    the Warp test must do the same so that the effective physics (OOB
    bounce-back vs. solid-wall early-return) is equivalent at boundaries.
    """
    import warp as wp

    flag_host = state.flag.numpy()
    phi_host = state.phi.numpy()
    mass_host = state.mass.numpy()

    for k in range(N):
        for j in range(N):
            for i in range(N):
                if i == 0 or i == N - 1 or j == 0 or j == N - 1 or k == 0 or k == N - 1:
                    flag_host[i, j, k] = C.CellFlag.TYPE_S
                    phi_host[i, j, k] = 0.0
                    mass_host[i, j, k] = 0.0

    wp.copy(state.flag, wp.array(flag_host, dtype=wp.uint8, device=state.flag.device))
    wp.copy(state.phi, wp.array(phi_host, dtype=float, device=state.phi.device))
    wp.copy(state.mass, wp.array(mass_host, dtype=float, device=state.mass.device))


def _run_steps_verbose(domain, steps, N):
    """Run `steps` domain steps, printing per-step rho/mass/phi at key cells."""
    z_split = N // 2
    stride = N * N * N

    # Cells to watch: (i=8, j=8) at various z depths
    si, sj = 8, 8
    watch_ks = [0, 4, 8, 12, z_split - 2, z_split - 1, z_split, z_split + 1, z_split + 2, 24, 28]

    print(f"\n=== Stepwise diagnostics for flat_interface ({N}^3, {steps} steps) ===")
    print(f"{'step':>5s} | {'k':>3s} | {'rho':>10s} | {'mass':>10s} | {'phi':>10s} | {'flag':>5s} | {'u_z':>10s}")
    print("-" * 70)

    for step_idx in range(steps + 1):
        if step_idx > 0:
            domain.step(dt=1.0)

        state = domain.state
        f_post = state.f_mom_post.numpy()
        mass3d = state.mass.numpy()
        phi3d = state.phi.numpy()
        flag3d = state.flag.numpy()

        for k in watch_ks:
            if k < 0 or k >= N:
                continue
            idx = si * N * N + sj * N + k
            rho = float(f_post[0 * stride + idx])
            uz = float(f_post[3 * stride + idx])
            mass_val = float(mass3d[si, sj, k])
            phi_val = float(phi3d[si, sj, k])
            flag_val = int(flag3d[si, sj, k])
            print(f"{step_idx:5d} | {k:3d} | {rho:10.6f} | {mass_val:10.6f} | {phi_val:10.6f} | {flag_val:#05x} | {uz:10.6f}")
        print("-" * 70)


def _run_steps(domain, steps):
    """Run `steps` domain steps and return the final state arrays."""
    for _ in range(steps):
        domain.step(dt=1.0)


# ============================================================================
# Cell-ordering conversion (ref k-major → Warp i-major)
# ============================================================================
# Reference C flat-index: idx_ref = k*N*N + j*N + i  (k slowest, i fastest)
# Warp flat-index:        idx_warp = i*N*N + j*N + k  (i slowest, k fastest)


def _reorder_scalar_field(golden_flat: "np.ndarray", N: int) -> "np.ndarray":
    """Convert a flat scalar field (N**3) from ref (k-major) to Warp (i-major).

    golden_flat[k*N*N + j*N + i]  →  out[i*N*N + j*N + k]
    """
    g3d = golden_flat.reshape(N, N, N)          # [k, j, i] in C order
    w3d = np.transpose(g3d, (2, 1, 0))           # [i, j, k]
    return w3d.ravel()


def _reorder_f_mom_post(golden_flat: "np.ndarray", N: int) -> "np.ndarray":
    """Convert f_mom_post (10*N**3 interleaved) from ref to Warp ordering.

    Layout: [mom0_cell0, mom0_cell1, ..., mom1_cell0, ...]
    """
    total = N * N * N
    out = np.empty_like(golden_flat)
    for m in range(10):
        out[m * total : (m + 1) * total] = _reorder_scalar_field(
            golden_flat[m * total : (m + 1) * total], N,
        )
    return out


# ============================================================================
# Comparison logic
# ============================================================================


def _compare_f_mom_post(golden, warped, stride, scene_name, rtol=1e-4, atol=1e-6):
    """Compare f_mom_post: interleaved (10*N) float32 arrays.

    Uses mixed absolute + relative tolerance: an element differs if
    ``abs(a - b) > atol + rtol * max(abs(a), abs(b))``.

    Returns
    -------
    str or None
        Error message if the comparison fails, ``None`` if it passes.
    """
    if golden.shape != warped.shape:
        return (f"[{scene_name}] f_mom_post shape mismatch: "
                f"{golden.shape} vs {warped.shape}")

    n = len(golden)
    g = np.asarray(golden, dtype=np.float64).ravel()
    w = np.asarray(warped, dtype=np.float64).ravel()
    a_g = np.abs(g)
    a_w = np.abs(w)
    diff = np.abs(g - w)
    thresh = atol + rtol * np.maximum(a_g, a_w)
    mismatches = int(np.sum(diff > thresh))
    denom = np.maximum(a_g, a_w)
    denom[denom == 0.0] = 1e-30
    max_err = float(np.max(diff / denom))

    if mismatches > 0:
        pct = 100.0 * mismatches / n
        return (f"[{scene_name}] f_mom_post: {mismatches}/{n} elements ({pct:.2f}%) "
                f"exceed tolerance (rtol={rtol}, atol={atol}), max rel err = {max_err:.2e}")
    return None


def _compare_flag(golden, warped, scene_name, N=None):
    """Flag must match bit-exact, except at domain boundary faces.

    Returns
    -------
    str or None
        Error message if interior cells differ, ``None`` if all clear.
    """
    if golden.shape != warped.shape:
        return f"[{scene_name}] flag shape mismatch: {golden.shape} vs {warped.shape}"

    diff_mask = golden != warped
    total_diffs = int(np.sum(diff_mask))

    if N is not None and total_diffs > 0:
        Nx, Ny, Nz = golden.shape
        on_boundary = np.zeros(golden.shape, dtype=bool)
        on_boundary[0, :, :] = True
        on_boundary[-1, :, :] = True
        on_boundary[:, 0, :] = True
        on_boundary[:, -1, :] = True
        on_boundary[:, :, 0] = True
        on_boundary[:, :, -1] = True

        boundary_diffs = int(np.sum(diff_mask & on_boundary))
        interior_diffs = total_diffs - boundary_diffs

        if boundary_diffs > 0:
            bidx = np.where(diff_mask & on_boundary)
            bdetails = "; ".join(
                f"({bidx[0][i]},{bidx[1][i]},{bidx[2][i]}) "
                f"ref={golden[bidx][i]:#x} warp={warped[bidx][i]:#x}"
                for i in range(min(3, len(bidx[0])))
            )
            print(f"  [{scene_name}] flag: {boundary_diffs} boundary-face "
                  f"mismatches expected (golden has TYPE_S walls), "
                  f"e.g. {bdetails}")

        if interior_diffs > 0:
            idx = np.where(diff_mask & ~on_boundary)
            details = "; ".join(
                f"({idx[0][i]},{idx[1][i]},{idx[2][i]}) "
                f"ref={golden[idx][i]:#x} warp={warped[idx][i]:#x}"
                for i in range(min(5, len(idx[0])))
            )
            return (f"[{scene_name}] flag: {interior_diffs} interior cells differ "
                    f"(first: {details})")
        return None
    elif total_diffs > 0:
        idx = np.where(diff_mask)
        details = "; ".join(
            f"({idx[0][i]},{idx[1][i]},{idx[2][i]}) "
            f"ref={golden[idx][i]:#x} warp={warped[idx][i]:#x}"
            for i in range(min(5, len(idx[0])))
        )
        return (f"[{scene_name}] flag: {total_diffs} cells differ "
                f"(first: {details})")
    return None


def _compare_float_field(golden, warped, scene_name, field_name, rtol=1e-4, atol=1e-6):
    """Compare a float scalar field (mass, phi).

    Returns
    -------
    str or None
        Error message if the comparison fails, ``None`` if it passes.
    """
    if golden.shape != warped.shape:
        return f"[{scene_name}] {field_name} shape mismatch: {golden.shape} vs {warped.shape}"
    g = np.asarray(golden, dtype=np.float64).ravel()
    w = np.asarray(warped, dtype=np.float64).ravel()
    a_g = np.abs(g)
    a_w = np.abs(w)
    diff = np.abs(g - w)
    thresh = atol + rtol * np.maximum(a_g, a_w)
    mismatches = int(np.sum(diff > thresh))
    denom = np.maximum(a_g, a_w)
    denom[denom == 0.0] = 1e-30
    max_err = float(np.max(diff / denom))

    if mismatches > 0:
        n = len(g)
        pct = 100.0 * mismatches / n
        return (f"[{scene_name}] {field_name}: {mismatches}/{n} ({pct:.2f}%) "
                f"exceed tolerance (rtol={rtol}, atol={atol}), max rel err = {max_err:.2e}")
    return None


def _compare_tag_matrix(golden, warped, scene_name):
    """Compare tag_matrix allowing label renumbering (permutation).

    Returns
    -------
    str or None
        Error message if the comparison fails, ``None`` if it passes.
    """
    if golden.shape != warped.shape:
        return f"[{scene_name}] tag_matrix shape mismatch: {golden.shape} vs {warped.shape}"

    g = golden.ravel()
    w = warped.ravel()

    g_labels = set(int(x) for x in np.unique(g) if x != -1)
    w_labels = set(int(x) for x in np.unique(w) if x != -1)

    if len(g_labels) != len(w_labels):
        return (f"[{scene_name}] tag_matrix: label count mismatch: "
                f"ref={len(g_labels)}, warp={len(w_labels)}")

    if len(g_labels) == 0:
        return None

    def label_map(arr):
        mapping = {}
        for i, v in enumerate(arr):
            vi = int(v)
            if vi != -1:
                mapping.setdefault(vi, set()).add(i)
        return mapping

    g_map = label_map(g)
    w_map = label_map(w)

    g_sets = sorted([frozenset(s) for s in g_map.values()], key=lambda s: min(s))
    w_sets = sorted([frozenset(s) for s in w_map.values()], key=lambda s: min(s))

    if g_sets != w_sets:
        g_partition = np.zeros(len(g), dtype=np.int32) - 1
        w_partition = np.zeros(len(w), dtype=np.int32) - 1
        for sid, s in enumerate(g_sets):
            for idx in s:
                g_partition[idx] = sid
        for sid, s in enumerate(w_sets):
            for idx in s:
                w_partition[idx] = sid
        mismatches = int(np.sum(g_partition != w_partition))
        return (f"[{scene_name}] tag_matrix: {mismatches} cells in different "
                f"label partitions after renumbering")
    return None


# ============================================================================
# Test class
# ============================================================================


class TestRegressionSurface:
    """Golden-data regression tests for Phase 2 surface pipeline."""

    @staticmethod
    def _make_model(_warp, N, omega=OMEGA_REF, gz=0.0, turbulence_factor=None):
        from wanphys._src.fluid.fluid_grid.home_fslbm.model import HomeFslbmModel

        kwargs = dict(
            fluid_grid_res=(N, N, N),
            fluid_grid_cell_size=1.0,
            omega=omega,
            gravity_z=gz,
            turbulence_radius=3,
        )
        if turbulence_factor is not None:
            kwargs["turbulence_factor"] = turbulence_factor
        return HomeFslbmModel(**kwargs)

    @staticmethod
    def _make_domain(_warp, model):
        from wanphys._src.fluid.fluid_grid.home_fslbm.domain import HomeFslbmDomain
        from wanphys._src.fluid.fluid_grid.home_fslbm.solver import HomeFslbmSolver

        solver = HomeFslbmSolver(model)
        domain = HomeFslbmDomain(model, solver=solver)
        domain.create_state()
        return domain

    def _check_scene(self, _warp, scene_name, N, omega=OMEGA_REF, gz=0.0, steps=5,
                     turbulence_factor=None, setup_fn=None, setup_kwargs=None):
        """Common test logic for a single scene.

        Parameters
        ----------
        scene_name : str
            Subdirectory name under golden_data/ (e.g. "droplet_r8").
        N, omega, gz, steps : passed to model and run loop.
        turbulence_factor : optional override for turbulence_factor.
        setup_fn : callable(domain, N, **kw) → (flag_host, phi_host, mass_host)
        """
        if setup_kwargs is None:
            setup_kwargs = {}

        model = self._make_model(_warp, N, omega=omega, gz=gz,
                                 turbulence_factor=turbulence_factor)
        domain = self._make_domain(_warp, model)

        setup_fn(domain, N, **setup_kwargs)
        _set_boundary_walls(domain.state, N)

        # ---- Step-by-step diagnostics (only for flat_interface for now) ----
        if scene_name == "flat_interface":
            _run_steps_verbose(domain, steps, N)
        else:
            _run_steps(domain, steps)

        golden = load_surface_golden(scene_name)
        state = domain.state

        # Reorder golden data from reference (k-major) to Warp (i-major) indexing
        golden["f_mom_post"] = _reorder_f_mom_post(golden["f_mom_post"], N)
        golden["flag"] = _reorder_scalar_field(golden["flag"], N).reshape(N, N, N).astype(np.uint8)
        golden["mass"] = _reorder_scalar_field(golden["mass"], N).reshape(N, N, N)
        golden["phi"] = _reorder_scalar_field(golden["phi"], N).reshape(N, N, N)
        golden["tag_matrix"] = _reorder_scalar_field(golden["tag_matrix"], N).reshape(N, N, N).astype(np.int32)

        stride = N * N * N

        # ---- Run ALL comparisons, collecting errors ----
        errors = []
        warped_f = state.f_mom_post.numpy().flatten()
        err = _compare_f_mom_post(golden["f_mom_post"], warped_f, stride, scene_name)
        if err: errors.append(err)

        warped_flag = state.flag.numpy()
        err = _compare_flag(golden["flag"], warped_flag, scene_name, N=N)
        if err: errors.append(err)

        warped_mass = state.mass.numpy()
        err = _compare_float_field(golden["mass"], warped_mass, scene_name, "mass")
        if err: errors.append(err)

        warped_phi = state.phi.numpy()
        err = _compare_float_field(golden["phi"], warped_phi, scene_name, "phi")
        if err: errors.append(err)

        warped_tag = state.tag_matrix.numpy()
        err = _compare_tag_matrix(golden["tag_matrix"], warped_tag, scene_name)
        if err: errors.append(err)

        if errors:
            summary = f"[{scene_name}] {len(errors)} comparison(s) failed:\n"
            for e in errors:
                summary += f"  {e}\n"
            raise AssertionError(summary)

    # ------------------------------------------------------------------
    # Standard scenes (8)
    # ------------------------------------------------------------------

    def test_droplet_r4(self, _warp):
        """R=4 sphere on 16^3, 5 steps."""
        self._check_scene(
            _warp, "droplet_r4", N=16, gz=0.0, steps=5,
            setup_fn=_setup_sphere_droplet,
            setup_kwargs={"R": 4.0},
        )

    def test_droplet_r8(self, _warp):
        """R=8 sphere on 32^3, 10 steps."""
        self._check_scene(
            _warp, "droplet_r8", N=32, gz=0.0, steps=10,
            setup_fn=_setup_sphere_droplet,
            setup_kwargs={"R": 8.0},
        )

    def test_droplet_r12(self, _warp):
        """R=12 sphere on 32^3, 10 steps."""
        self._check_scene(
            _warp, "droplet_r12", N=32, gz=0.0, steps=10,
            setup_fn=_setup_sphere_droplet,
            setup_kwargs={"R": 12.0},
        )

    def test_flat_interface(self, _warp):
        """Flat interface at z=16 on 32^3, 10 steps."""
        self._check_scene(
            _warp, "flat_interface", N=32, gz=0.0, steps=10,
            setup_fn=_setup_flat_interface,
            setup_kwargs={"z_split": 16},
        )

    def test_near_droplets(self, _warp):
        """Two R=6 droplets centre-dist 14 on 32^3, 20 steps."""
        self._check_scene(
            _warp, "near_droplets", N=32, gz=0.0, steps=20,
            setup_fn=_setup_near_droplets,
            setup_kwargs={"R": 6.0, "center_dist": 14.0},
        )

    def test_ellipsoid(self, _warp):
        """Ellipsoid rx=10 ry=6 rz=6 on 32^3, 50 steps."""
        self._check_scene(
            _warp, "ellipsoid", N=32, gz=0.0, steps=50,
            setup_fn=_setup_ellipsoid,
            setup_kwargs={"rx": 10.0, "ry": 6.0, "rz": 6.0},
        )

    def test_falling_droplet(self, _warp):
        """R=6 falling droplet gz=-0.001 on 32^3, 30 steps."""
        self._check_scene(
            _warp, "falling_droplet", N=32, gz=-0.001, steps=30,
            setup_fn=_setup_sphere_droplet,
            setup_kwargs={"R": 6.0},
        )

    def test_droplet_wall(self, _warp):
        """R=6 droplet near z=0 wall on 32^3, 10 steps."""
        def _setup(domain, N, R=6.0, z_wall=0):
            import warp as wp

            cz = z_wall + R  # droplet bottom touching wall
            flag_host, phi_host, mass_host = _setup_sphere_droplet(
                domain, N, R, cx=N / 2, cy=N / 2, cz=cz,
            )
            # Set z=0 plane as TYPE_S
            for j in range(N):
                for i in range(N):
                    flag_host[i, j, 0] = C.CellFlag.TYPE_S
                    phi_host[i, j, 0] = 0.0
                    mass_host[i, j, 0] = 0.0
            state = domain.state
            wp.copy(state.flag, wp.array(flag_host, dtype=wp.uint8, device=state.flag.device))
            wp.copy(state.phi, wp.array(phi_host, dtype=float, device=state.phi.device))
            wp.copy(state.mass, wp.array(mass_host, dtype=float, device=state.mass.device))

        self._check_scene(
            _warp, "droplet_wall", N=32, gz=0.0, steps=10,
            setup_fn=_setup,
        )

    # ------------------------------------------------------------------
    # Parameter-variation scenes (2)
    # ------------------------------------------------------------------

    def test_droplet_tau055(self, _warp):
        """R=8 sphere, 20 steps. Reference: labma=1/0.55≈1.818, collision omega≈1.998."""
        self._check_scene(
            _warp, "droplet_tau055", N=32, gz=0.0, steps=20,
            setup_fn=_setup_sphere_droplet,
            setup_kwargs={"R": 8.0},
        )

    def test_droplet_tau2(self, _warp):
        """R=8 sphere, 20 steps. Reference: labma=0.5, collision omega≈1.998."""
        self._check_scene(
            _warp, "droplet_tau2", N=32, gz=0.0, steps=20,
            setup_fn=_setup_sphere_droplet,
            setup_kwargs={"R": 8.0},
        )

# ============================================================================
# Diagnostic: step-by-step comparison for droplet_r8
# ============================================================================


def _load_surface_golden_path(scene_dir):
    """Load surface golden data from an explicit path (supports subdirectories)."""
    import numpy as np
    from pathlib import Path
    sd = Path(scene_dir)
    return {
        "f_mom_post": np.loadtxt(sd / "f_mom_post.txt", dtype=np.float32),
        "flag":       np.loadtxt(sd / "flag.txt", dtype=np.int32),
        "mass":       np.loadtxt(sd / "mass.txt", dtype=np.float32),
        "phi":        np.loadtxt(sd / "phi.txt", dtype=np.float32),
        "tag_matrix": np.loadtxt(sd / "tag_matrix.txt", dtype=np.int32),
    }


def _first_diff_report(golden, warped, field_name, N, max_cells=10):
    """Print the first *max_cells* cells where golden != warped.

    Uses the same tolerance as _compare_float_field / _compare_f_mom_post.
    """
    rtol = 1e-4
    atol = 1e-6

    g = golden.reshape(N, N, N)
    w = warped.reshape(N, N, N)

    abs_diff = np.abs(g.astype(np.float64) - w.astype(np.float64))
    max_val = np.maximum(np.abs(g.astype(np.float64)),
                         np.abs(w.astype(np.float64)))
    max_val[max_val == 0.0] = 1e-30
    threshold = atol + rtol * max_val
    mask = abs_diff > threshold

    diff_count = int(np.sum(mask))
    if diff_count == 0:
        print(f"  [{field_name}] all {N**3} cells match (rtol={rtol}, atol={atol})")
        return 0

    pct = 100.0 * diff_count / (N ** 3)
    print(f"  [{field_name}] {diff_count}/{N**3} cells differ ({pct:.4f}%)")
    idx = np.where(mask)
    for n in range(min(max_cells, len(idx[0]))):
        ii, jj, kk = idx[0][n], idx[1][n], idx[2][n]
        gv = g[ii, jj, kk]
        wv = w[ii, jj, kk]
        ad = abs_diff[ii, jj, kk]
        print(f"    ({ii:2d},{jj:2d},{kk:2d}) "
              f"golden={gv:.8e}  warp={wv:.8e}  "
              f"abs={ad:.2e}")
    return diff_count


def _check_diag_step(_warp, scene_name, N, steps, setup_fn, setup_kwargs):
    """Run *steps* and compare against golden at that step.

    Returns True if all fields match.
    """
    import warp as wp
    from wanphys._src.fluid.fluid_grid.home_fslbm.model import HomeFslbmModel
    from wanphys._src.fluid.fluid_grid.home_fslbm.solver import HomeFslbmSolver
    from wanphys._src.fluid.fluid_grid.home_fslbm.domain import HomeFslbmDomain
    from pathlib import Path

    model = HomeFslbmModel(
        fluid_grid_res=(N, N, N),
        fluid_grid_cell_size=1.0,
        omega=OMEGA_REF,
        gravity_z=0.0,
        turbulence_radius=3,
    )
    solver = HomeFslbmSolver(model)
    domain = HomeFslbmDomain(model, solver=solver)
    domain.create_state()

    setup_fn(domain, N, **setup_kwargs)
    _set_boundary_walls(domain.state, N)

    for _ in range(steps):
        domain.step(dt=1.0)

    state = domain.state

    golden_dir = Path(__file__).parent / "golden_data" / scene_name / f"step_{steps}"
    if not golden_dir.exists():
        raise FileNotFoundError(
            f"Golden data not found at {golden_dir}. "
            f"Run the updated export_solver_golden.cpp first."
        )
    golden = _load_surface_golden_path(golden_dir)
    stride = N * N * N

    # Reorder golden data
    g_fmom = _reorder_f_mom_post(golden["f_mom_post"], N)
    g_flag = _reorder_scalar_field(golden["flag"], N).reshape(N, N, N).astype(np.uint8)
    g_mass = _reorder_scalar_field(golden["mass"], N).reshape(N, N, N)
    g_phi = _reorder_scalar_field(golden["phi"], N).reshape(N, N, N)

    print(f"\n========== step {steps} comparison ==========")

    errors = 0

    # flag (bit-exact, ignoring boundary faces)
    w_flag = state.flag.numpy().reshape(N, N, N)
    diff_mask = g_flag != w_flag
    total_diffs = int(np.sum(diff_mask))
    if total_diffs > 0:
        on_boundary = np.zeros((N, N, N), dtype=bool)
        on_boundary[0, :, :] = True; on_boundary[-1, :, :] = True
        on_boundary[:, 0, :] = True; on_boundary[:, -1, :] = True
        on_boundary[:, :, 0] = True; on_boundary[:, :, -1] = True
        interior = int(np.sum(diff_mask & ~on_boundary))
        if interior > 0:
            idx = np.where(diff_mask & ~on_boundary)
            details = "; ".join(
                f"({idx[0][i]},{idx[1][i]},{idx[2][i]}) "
                f"ref={g_flag[idx][i]:#x} warp={w_flag[idx][i]:#x}"
                for i in range(min(5, len(idx[0])))
            )
            print(f"  [flag] {interior} interior cells differ (first: {details})")
            errors += 1
        else:
            print(f"  [flag] {total_diffs} boundary-face mismatches (expected)")
    else:
        print(f"  [flag] all match")

    # mass, phi
    errors += _first_diff_report(g_mass, state.mass.numpy(), "mass", N)
    errors += _first_diff_report(g_phi, state.phi.numpy(), "phi", N)

    # f_mom_post
    w_fmom = state.f_mom_post.numpy().flatten()
    g_fmom_flat = np.asarray(g_fmom, dtype=np.float32).ravel()
    w_fmom_flat = np.asarray(w_fmom, dtype=np.float32).ravel()
    abs_diff = np.abs(
        g_fmom_flat.astype(np.float64) - w_fmom_flat.astype(np.float64)
    )
    max_val = np.maximum(
        np.abs(g_fmom_flat.astype(np.float64)),
        np.abs(w_fmom_flat.astype(np.float64)),
    )
    max_val[max_val == 0.0] = 1e-30
    thresh = 1e-6 + 1e-4 * max_val
    n_mm = int(np.sum(abs_diff > thresh))
    if n_mm > 0:
        pct = 100.0 * n_mm / len(g_fmom_flat)
        rel_err = abs_diff / max_val
        max_rel = float(np.max(rel_err))
        print(f"  [f_mom_post] {n_mm}/{len(g_fmom_flat)} ({pct:.2f}%) "
              f"differ, max rel err={max_rel:.2e}")
        # Show first 5 differing moment elements
        bad = np.where(abs_diff > thresh)[0]
        for n in range(min(5, len(bad))):
            bi = bad[n]
            mom = bi // stride
            cell = bi % stride
            i = cell // (N * N)
            j = (cell // N) % N
            k = cell % N
            print(f"    mom[{mom}] cell({i},{j},{k}) "
                  f"golden={g_fmom_flat[bi]:.8e} warp={w_fmom_flat[bi]:.8e} "
                  f"abs={abs_diff[bi]:.3e} rel={rel_err[bi]:.3e}")
        errors += 1
    else:
        print(f"  [f_mom_post] all match")

    return errors == 0


class TestDiagnosticDropletR8:
    """Step-by-step diagnostic for droplet_r8 (32^3).

    Requires golden data generated by the updated export_solver_golden.cpp
    (gen_droplet_r8_diag) placed under golden_data/droplet_r8_diag/.
    """

    @pytest.fixture(scope="class")
    def _warp(self):
        import warp as wp
        return wp

    def test_step0_initial(self, _warp):
        """Compare Warp initial state vs golden step 0."""
        assert _check_diag_step(
            _warp, "droplet_r8_diag", N=32, steps=0,
            setup_fn=_setup_sphere_droplet, setup_kwargs={"R": 8.0},
        )

    def test_step1_single(self, _warp):
        """Compare Warp after 1 step vs golden step 1."""
        assert _check_diag_step(
            _warp, "droplet_r8_diag", N=32, steps=1,
            setup_fn=_setup_sphere_droplet, setup_kwargs={"R": 8.0},
        )

    def test_step2(self, _warp):
        """Compare Warp after 2 steps vs golden step 2."""
        assert _check_diag_step(
            _warp, "droplet_r8_diag", N=32, steps=2,
            setup_fn=_setup_sphere_droplet, setup_kwargs={"R": 8.0},
        )
