# SPDX-FileCopyrightText: Copyright (c) 2025 WanPhys Developers
# SPDX-License-Identifier: Apache-2.0

"""Phase 2 golden-data regression tests for HOME-FSLBM free-surface.

Each test constructs a scene (droplet / flat interface / ellipsoid / …),
runs the full ``stream_collide_bvh + surface_1/2/3`` pipeline for a fixed
number of steps, and compares the final state against reference CUDA C++
output (golden ``.txt`` files).

The golden data is generated by the extended ``export_solver_golden.cpp``
in ``docs/papers/`` and stored as per-scene subdirectories under
``tests/golden_data/``.

.. note::

    **PLIC curvature offset**: the reference code and Warp share the same
    Monge-patch curvature formula with identical PLIC offset behaviour.
    The full-state regression tests below implicitly validate curvature
    (it feeds into the collision step via surface-tension Guo forcing),
    so matching f_mom_post / mass / phi / flag constitutes an end-to-end
    curvature verification.  Explicit cell-by-cell curvature comparison
    is in the companion ``test_regression_curvature.py``.
"""

from __future__ import annotations

import numpy as np
import pytest

from wanphys._src.fluid.fluid_grid.home_fslbm import constants as C
from wanphys._src.fluid.fluid_grid.home_fslbm.tests.conftest import (
    load_surface_golden,
)


# ============================================================================
# Fixtures
# ============================================================================


@pytest.fixture(scope="module")
def _warp():
    import warp as wp
    return wp


# ============================================================================
# Helpers
# ============================================================================


def _setup_sphere_droplet(domain, N, R, cx=None, cy=None, cz=None):
    """Initialise flag/phi/mass for a sphere droplet.

    Uses phi = clamp((R - dist) / delta + 0.5, 0, 1) with delta = 1.5 dx.
    """
    import warp as wp

    if cx is None:
        cx = N / 2
    if cy is None:
        cy = N / 2
    if cz is None:
        cz = N / 2

    delta = 1.5
    phi_host = np.zeros((N, N, N), dtype=np.float32)
    flag_host = np.zeros((N, N, N), dtype=np.uint8)
    mass_host = np.zeros((N, N, N), dtype=np.float32)

    for k in range(N):
        for j in range(N):
            for i in range(N):
                dx = i - cx
                dy = j - cy
                dz = k - cz
                dist = np.sqrt(dx * dx + dy * dy + dz * dz)
                phi_raw = (R - dist) / delta + 0.5
                phi_val = max(0.0, min(1.0, phi_raw))
                phi_host[i, j, k] = phi_val
                if phi_val >= 1.0 - 1e-6:
                    flag_host[i, j, k] = C.CellFlag.TYPE_F
                    mass_host[i, j, k] = 1.0
                elif phi_val <= 1e-6:
                    flag_host[i, j, k] = C.CellFlag.TYPE_G
                    mass_host[i, j, k] = 0.0
                else:
                    flag_host[i, j, k] = C.CellFlag.TYPE_I
                    mass_host[i, j, k] = phi_val

    state = domain.state
    wp.copy(state.flag, wp.array(flag_host, dtype=wp.uint8, device=state.flag.device))
    wp.copy(state.phi, wp.array(phi_host, dtype=float, device=state.phi.device))
    wp.copy(state.mass, wp.array(mass_host, dtype=float, device=state.mass.device))
    _init_rest_state(domain, N)
    return flag_host, phi_host, mass_host


def _setup_flat_interface(domain, N, z_split=None):
    """Initialise a flat horizontal interface at z = z_split."""
    import warp as wp

    if z_split is None:
        z_split = N // 2

    delta = 1.5
    phi_host = np.zeros((N, N, N), dtype=np.float32)
    flag_host = np.zeros((N, N, N), dtype=np.uint8)
    mass_host = np.zeros((N, N, N), dtype=np.float32)

    for k in range(N):
        phi_raw = (z_split - k) / delta + 0.5
        phi_val = max(0.0, min(1.0, phi_raw))
        phi_host[:, :, k] = phi_val
        if phi_val >= 1.0 - 1e-6:
            flag_host[:, :, k] = C.CellFlag.TYPE_F
            mass_host[:, :, k] = 1.0
        elif phi_val <= 1e-6:
            flag_host[:, :, k] = C.CellFlag.TYPE_G
            mass_host[:, :, k] = 0.0
        else:
            flag_host[:, :, k] = C.CellFlag.TYPE_I
            mass_host[:, :, k] = phi_val

    state = domain.state
    wp.copy(state.flag, wp.array(flag_host, dtype=wp.uint8, device=state.flag.device))
    wp.copy(state.phi, wp.array(phi_host, dtype=float, device=state.phi.device))
    wp.copy(state.mass, wp.array(mass_host, dtype=float, device=state.mass.device))
    _init_rest_state(domain, N)
    return flag_host, phi_host, mass_host


def _setup_near_droplets(domain, N, R, center_dist):
    """Two spheres of radius R, centres separated by center_dist along x."""
    import warp as wp

    cx1 = N / 2 - center_dist / 2
    cx2 = N / 2 + center_dist / 2
    cy = N / 2
    cz = N / 2

    delta = 1.5
    phi_host = np.zeros((N, N, N), dtype=np.float32)
    flag_host = np.zeros((N, N, N), dtype=np.uint8)
    mass_host = np.zeros((N, N, N), dtype=np.float32)

    for k in range(N):
        for j in range(N):
            for i in range(N):
                d1 = np.sqrt((i - cx1) ** 2 + (j - cy) ** 2 + (k - cz) ** 2)
                d2 = np.sqrt((i - cx2) ** 2 + (j - cy) ** 2 + (k - cz) ** 2)
                phi1 = (R - d1) / delta + 0.5
                phi2 = (R - d2) / delta + 0.5
                phi_raw = max(phi1, phi2)
                phi_val = max(0.0, min(1.0, phi_raw))
                phi_host[i, j, k] = phi_val
                if phi_val >= 1.0 - 1e-6:
                    flag_host[i, j, k] = C.CellFlag.TYPE_F
                    mass_host[i, j, k] = 1.0
                elif phi_val <= 1e-6:
                    flag_host[i, j, k] = C.CellFlag.TYPE_G
                    mass_host[i, j, k] = 0.0
                else:
                    flag_host[i, j, k] = C.CellFlag.TYPE_I
                    mass_host[i, j, k] = phi_val

    state = domain.state
    wp.copy(state.flag, wp.array(flag_host, dtype=wp.uint8, device=state.flag.device))
    wp.copy(state.phi, wp.array(phi_host, dtype=float, device=state.phi.device))
    wp.copy(state.mass, wp.array(mass_host, dtype=float, device=state.mass.device))
    _init_rest_state(domain, N)
    return flag_host, phi_host, mass_host


def _setup_ellipsoid(domain, N, rx, ry, rz):
    """Ellipsoid (rx, ry, rz) at centre."""
    import warp as wp

    cx = N / 2
    cy = N / 2
    cz = N / 2
    delta = 1.5

    phi_host = np.zeros((N, N, N), dtype=np.float32)
    flag_host = np.zeros((N, N, N), dtype=np.uint8)
    mass_host = np.zeros((N, N, N), dtype=np.float32)

    for k in range(N):
        for j in range(N):
            for i in range(N):
                dx = (i - cx) / rx
                dy = (j - cy) / ry
                dz = (k - cz) / rz
                dist = np.sqrt(dx * dx + dy * dy + dz * dz)
                phi_raw = (1.0 - dist) * rx / delta + 0.5
                phi_val = max(0.0, min(1.0, phi_raw))
                phi_host[i, j, k] = phi_val
                if phi_val >= 1.0 - 1e-6:
                    flag_host[i, j, k] = C.CellFlag.TYPE_F
                    mass_host[i, j, k] = 1.0
                elif phi_val <= 1e-6:
                    flag_host[i, j, k] = C.CellFlag.TYPE_G
                    mass_host[i, j, k] = 0.0
                else:
                    flag_host[i, j, k] = C.CellFlag.TYPE_I
                    mass_host[i, j, k] = phi_val

    state = domain.state
    wp.copy(state.flag, wp.array(flag_host, dtype=wp.uint8, device=state.flag.device))
    wp.copy(state.phi, wp.array(phi_host, dtype=float, device=state.phi.device))
    wp.copy(state.mass, wp.array(mass_host, dtype=float, device=state.mass.device))
    _init_rest_state(domain, N)
    return flag_host, phi_host, mass_host


def _init_rest_state(domain, N):
    """Set f_mom/f_mom_post to equilibrium (rho=1, u=0).

    .. note::

        ``tag_matrix`` is left at the Warp default (zeros).  This is
        intentional: zero-valued tags trigger the strain-rate turbulence
        path, producing the same effective omega (approx 1.998) as the
        reference code's hardcoded ``1/((1e-4)*3+0.5)``.  If tags were
        set to -1, Warp would use ``model.omega`` (default 1.0) while
        the reference still uses 1.998, causing a collision-relaxation
        mismatch.
    """
    import warp as wp

    state = domain.state
    total = N * N * N

    # Equilibrium moments: rho=1, u=0, S_ab=0
    f_data = np.zeros(10 * total, dtype=np.float32)
    f_data[0 * total:1 * total] = 1.0  # rho
    # u = 0, S = 0 (already zero)

    f_mom_arr = wp.array(f_data, dtype=float, device=state.f_mom.device)
    wp.copy(state.f_mom, f_mom_arr)
    wp.copy(state.f_mom_post, f_mom_arr)

    # massex = 0
    state.massex.zero_()

    # force = 0 (will be set by gravity in step)
    state.force_x.zero_()
    state.force_y.zero_()
    state.force_z.zero_()

    # delta_phi = 0
    state.delta_phi.zero_()


def _run_steps(domain, steps):
    """Run `steps` domain steps and return the final state arrays."""
    for _ in range(steps):
        domain.step(dt=1.0)


# ============================================================================
# Cell-ordering conversion (ref k-major → Warp i-major)
# ============================================================================
# Reference C flat-index: idx_ref = k*N*N + j*N + i  (k slowest, i fastest)
# Warp flat-index:        idx_warp = i*N*N + j*N + k  (i slowest, k fastest)


def _reorder_scalar_field(golden_flat: "np.ndarray", N: int) -> "np.ndarray":
    """Convert a flat scalar field (N**3) from ref (k-major) to Warp (i-major).

    golden_flat[k*N*N + j*N + i]  →  out[i*N*N + j*N + k]
    """
    g3d = golden_flat.reshape(N, N, N)          # [k, j, i] in C order
    w3d = np.transpose(g3d, (2, 1, 0))           # [i, j, k]
    return w3d.ravel()


def _reorder_f_mom_post(golden_flat: "np.ndarray", N: int) -> "np.ndarray":
    """Convert f_mom_post (10*N**3 interleaved) from ref to Warp ordering.

    Layout: [mom0_cell0, mom0_cell1, ..., mom1_cell0, ...]
    """
    total = N * N * N
    out = np.empty_like(golden_flat)
    for m in range(10):
        out[m * total : (m + 1) * total] = _reorder_scalar_field(
            golden_flat[m * total : (m + 1) * total], N,
        )
    return out


# ============================================================================
# Comparison logic
# ============================================================================


def _compare_f_mom_post(golden, warped, stride, scene_name, tol=1e-4):
    """Compare f_mom_post: interleaved (10*N) float32 arrays.

    Uses element-wise relative error.  Near-zero values use absolute tolerance.
    """
    assert golden.shape == warped.shape, \
        f"[{scene_name}] f_mom_post shape mismatch: {golden.shape} vs {warped.shape}"

    n = len(golden)
    mismatches = 0
    max_err = 0.0
    for i in range(n):
        a = float(golden[i])
        b = float(warped[i])
        denom = max(abs(a), abs(b), 1e-10)
        rel_err = abs(a - b) / denom
        if denom <= 1e-10:
            # Both near zero — use absolute tolerance
            if abs(a - b) > 1e-10:
                mismatches += 1
        elif rel_err > tol:
            mismatches += 1
            if rel_err > max_err:
                max_err = rel_err

    if mismatches > 0:
        pct = 100.0 * mismatches / n
        raise AssertionError(
            f"[{scene_name}] f_mom_post: {mismatches}/{n} elements ({pct:.2f}%) "
            f"exceed tolerance {tol}, max rel err = {max_err:.2e}"
        )


def _compare_flag(golden, warped, scene_name):
    """Flag must match bit-exact."""
    assert golden.shape == warped.shape, \
        f"[{scene_name}] flag shape mismatch"
    mismatches = int(np.sum(golden != warped))
    if mismatches > 0:
        # Show first few mismatches
        idx = np.where(golden != warped)
        details = "; ".join(
            f"({idx[0][i]},{idx[1][i]},{idx[2][i]}) ref={golden[idx][i]:#x} warp={warped[idx][i]:#x}"
            for i in range(min(5, len(idx[0])))
        )
        raise AssertionError(
            f"[{scene_name}] flag: {mismatches} cells differ "
            f"(first: {details})"
        )


def _compare_float_field(golden, warped, scene_name, field_name, tol=1e-4):
    """Compare a float scalar field (mass, phi)."""
    assert golden.shape == warped.shape, \
        f"[{scene_name}] {field_name} shape mismatch"
    g = golden.ravel()
    w = warped.ravel()
    n = len(g)
    mismatches = 0
    max_err = 0.0
    for i in range(n):
        a = float(g[i])
        b = float(w[i])
        denom = max(abs(a), abs(b), 1e-10)
        rel_err = abs(a - b) / denom
        if denom <= 1e-10:
            if abs(a - b) > 1e-10:
                mismatches += 1
        elif rel_err > tol:
            mismatches += 1
            if rel_err > max_err:
                max_err = rel_err

    if mismatches > 0:
        pct = 100.0 * mismatches / n
        raise AssertionError(
            f"[{scene_name}] {field_name}: {mismatches}/{n} ({pct:.2f}%) "
            f"exceed tolerance {tol}, max rel err = {max_err:.2e}"
        )


def _compare_tag_matrix(golden, warped, scene_name):
    """Compare tag_matrix allowing label renumbering (permutation).

    The reference code and Warp may assign different bubble IDs, but the
    topological equivalence (which cells share the same label) must match.
    """
    assert golden.shape == warped.shape, \
        f"[{scene_name}] tag_matrix shape mismatch"

    g = golden.ravel()
    w = warped.ravel()

    # Build label set (excluding -1 = no tag)
    g_labels = set(int(x) for x in np.unique(g) if x != -1)
    w_labels = set(int(x) for x in np.unique(w) if x != -1)

    if len(g_labels) != len(w_labels):
        raise AssertionError(
            f"[{scene_name}] tag_matrix: label count mismatch: "
            f"ref={len(g_labels)}, warp={len(w_labels)}"
        )

    if len(g_labels) == 0:
        # Both have only -1 labels — trivially match
        return

    # Build label→cell-set mapping
    def label_map(arr):
        mapping = {}
        for i, v in enumerate(arr):
            vi = int(v)
            if vi != -1:
                mapping.setdefault(vi, set()).add(i)
        return mapping

    g_map = label_map(g)
    w_map = label_map(w)

    # Extract cell-sets as frozensets for comparison
    g_sets = sorted([frozenset(s) for s in g_map.values()], key=lambda s: min(s))
    w_sets = sorted([frozenset(s) for s in w_map.values()], key=lambda s: min(s))

    if g_sets != w_sets:
        # Count mismatched cells
        g_partition = np.zeros(len(g), dtype=np.int32) - 1
        w_partition = np.zeros(len(w), dtype=np.int32) - 1
        for sid, s in enumerate(g_sets):
            for idx in s:
                g_partition[idx] = sid
        for sid, s in enumerate(w_sets):
            for idx in s:
                w_partition[idx] = sid
        mismatches = int(np.sum(g_partition != w_partition))
        raise AssertionError(
            f"[{scene_name}] tag_matrix: {mismatches} cells in different "
            f"label partitions after renumbering"
        )


# ============================================================================
# Test class
# ============================================================================


class TestRegressionSurface:
    """Golden-data regression tests for Phase 2 surface pipeline."""

    @staticmethod
    def _make_model(_warp, N, omega=1.0, gz=0.0):
        from wanphys._src.fluid.fluid_grid.home_fslbm.model import HomeFslbmModel

        return HomeFslbmModel(
            fluid_grid_res=(N, N, N),
            fluid_grid_cell_size=1.0,
            omega=omega,
            gravity_z=gz,
            turbulence_radius=3,
        )

    @staticmethod
    def _make_domain(_warp, model):
        from wanphys._src.fluid.fluid_grid.home_fslbm.domain import HomeFslbmDomain
        from wanphys._src.fluid.fluid_grid.home_fslbm.solver import HomeFslbmSolver

        solver = HomeFslbmSolver(model)
        domain = HomeFslbmDomain(model, solver=solver)
        domain.create_state()
        return domain

    def _check_scene(self, _warp, scene_name, N, omega, gz, steps,
                     setup_fn, setup_kwargs=None):
        """Common test logic for a single scene.

        Parameters
        ----------
        scene_name : str
            Subdirectory name under golden_data/ (e.g. "droplet_r8").
        N, omega, gz, steps : passed to model and run loop.
        setup_fn : callable(domain, N, **kw) → (flag_host, phi_host, mass_host)
        """
        if setup_kwargs is None:
            setup_kwargs = {}

        model = self._make_model(_warp, N, omega=omega, gz=gz)
        domain = self._make_domain(_warp, model)

        setup_fn(domain, N, **setup_kwargs)

        _run_steps(domain, steps)

        golden = load_surface_golden(scene_name)
        state = domain.state

        # Reorder golden data from reference (k-major) to Warp (i-major) indexing
        golden["f_mom_post"] = _reorder_f_mom_post(golden["f_mom_post"], N)
        golden["flag"] = _reorder_scalar_field(golden["flag"], N).reshape(N, N, N).astype(np.uint8)
        golden["mass"] = _reorder_scalar_field(golden["mass"], N).reshape(N, N, N)
        golden["phi"] = _reorder_scalar_field(golden["phi"], N).reshape(N, N, N)
        golden["tag_matrix"] = _reorder_scalar_field(golden["tag_matrix"], N).reshape(N, N, N).astype(np.int32)

        stride = N * N * N

        # Compare f_mom_post
        warped_f = state.f_mom_post.numpy().flatten()
        _compare_f_mom_post(golden["f_mom_post"], warped_f, stride, scene_name)

        # Compare flag
        warped_flag = state.flag.numpy()
        _compare_flag(golden["flag"], warped_flag, scene_name)

        # Compare mass
        warped_mass = state.mass.numpy()
        _compare_float_field(golden["mass"], warped_mass, scene_name, "mass")

        # Compare phi
        warped_phi = state.phi.numpy()
        _compare_float_field(golden["phi"], warped_phi, scene_name, "phi")

        # Compare tag_matrix (label-renumbering tolerant)
        warped_tag = state.tag_matrix.numpy()
        _compare_tag_matrix(golden["tag_matrix"], warped_tag, scene_name)

    # ------------------------------------------------------------------
    # Standard scenes (8)
    # ------------------------------------------------------------------

    def test_droplet_r4(self, _warp):
        """R=4 sphere on 16^3, 5 steps."""
        self._check_scene(
            _warp, "droplet_r4", N=16, omega=1.0, gz=0.0, steps=5,
            setup_fn=_setup_sphere_droplet,
            setup_kwargs={"R": 4.0},
        )

    def test_droplet_r8(self, _warp):
        """R=8 sphere on 32^3, 10 steps."""
        self._check_scene(
            _warp, "droplet_r8", N=32, omega=1.0, gz=0.0, steps=10,
            setup_fn=_setup_sphere_droplet,
            setup_kwargs={"R": 8.0},
        )

    def test_droplet_r12(self, _warp):
        """R=12 sphere on 32^3, 10 steps."""
        self._check_scene(
            _warp, "droplet_r12", N=32, omega=1.0, gz=0.0, steps=10,
            setup_fn=_setup_sphere_droplet,
            setup_kwargs={"R": 12.0},
        )

    def test_flat_interface(self, _warp):
        """Flat interface at z=16 on 32^3, 10 steps."""
        self._check_scene(
            _warp, "flat_interface", N=32, omega=1.0, gz=0.0, steps=10,
            setup_fn=_setup_flat_interface,
            setup_kwargs={"z_split": 16},
        )

    def test_near_droplets(self, _warp):
        """Two R=6 droplets centre-dist 14 on 32^3, 20 steps."""
        self._check_scene(
            _warp, "near_droplets", N=32, omega=1.0, gz=0.0, steps=20,
            setup_fn=_setup_near_droplets,
            setup_kwargs={"R": 6.0, "center_dist": 14.0},
        )

    def test_ellipsoid(self, _warp):
        """Ellipsoid rx=10 ry=6 rz=6 on 32^3, 50 steps."""
        self._check_scene(
            _warp, "ellipsoid", N=32, omega=1.0, gz=0.0, steps=50,
            setup_fn=_setup_ellipsoid,
            setup_kwargs={"rx": 10.0, "ry": 6.0, "rz": 6.0},
        )

    def test_falling_droplet(self, _warp):
        """R=6 falling droplet gz=-0.001 on 32^3, 30 steps."""
        self._check_scene(
            _warp, "falling_droplet", N=32, omega=1.0, gz=-0.001, steps=30,
            setup_fn=_setup_sphere_droplet,
            setup_kwargs={"R": 6.0},
        )

    def test_droplet_wall(self, _warp):
        """R=6 droplet near z=0 wall on 32^3, 10 steps."""
        def _setup(domain, N, R=6.0, z_wall=0):
            import warp as wp

            cz = z_wall + R  # droplet bottom touching wall
            flag_host, phi_host, mass_host = _setup_sphere_droplet(
                domain, N, R, cx=N / 2, cy=N / 2, cz=cz,
            )
            # Set z=0 plane as TYPE_S
            for j in range(N):
                for i in range(N):
                    flag_host[i, j, 0] = C.CellFlag.TYPE_S
                    phi_host[i, j, 0] = 0.0
                    mass_host[i, j, 0] = 0.0
            state = domain.state
            wp.copy(state.flag, wp.array(flag_host, dtype=wp.uint8, device=state.flag.device))
            wp.copy(state.phi, wp.array(phi_host, dtype=float, device=state.phi.device))
            wp.copy(state.mass, wp.array(mass_host, dtype=float, device=state.mass.device))

        self._check_scene(
            _warp, "droplet_wall", N=32, omega=1.0, gz=0.0, steps=10,
            setup_fn=_setup,
        )

    # ------------------------------------------------------------------
    # Parameter-variation scenes (2)
    # ------------------------------------------------------------------

    def test_droplet_tau055(self, _warp):
        """R=8 sphere omega=1/0.55≈1.818 on 32^3, 20 steps (low viscosity)."""
        omega = 1.0 / 0.55  # ≈1.818
        self._check_scene(
            _warp, "droplet_tau055", N=32, omega=omega, gz=0.0, steps=20,
            setup_fn=_setup_sphere_droplet,
            setup_kwargs={"R": 8.0},
        )

    def test_droplet_tau2(self, _warp):
        """R=8 sphere omega=0.5 on 32^3, 20 steps (high viscosity)."""
        self._check_scene(
            _warp, "droplet_tau2", N=32, omega=0.5, gz=0.0, steps=20,
            setup_fn=_setup_sphere_droplet,
            setup_kwargs={"R": 8.0},
        )