# SPDX-FileCopyrightText: Copyright (c) 2026 WanPhys Developers
# SPDX-License-Identifier: Apache-2.0

"""Moment-encoded D3Q27 lattice Boltzmann foundations.

This package is intentionally independent from the legacy ``lbm`` package.
The public API will grow only as each HOME-LBM stage gains a verification
suite; the legacy solver remains available as a regression reference.
"""

from .collision import collide_central_moments
from .boundary import linear_bouzidi_reflection
from .constants import D3Q27_DIRECTIONS, D3Q27_OPPOSITE, D3Q27_WEIGHTS, MOMENT_COUNT
from .cut_link import CutLinkBuffer
from .domain import HomeLbmDomain
from .diagnostics import HomeLbmDiagnostics
from .model import HomeLbmModel
from .lubrication import SphereWallLubrication, SphereWallLubricationConfig
from .motion import RigidMotionPredictor
from .quantization import (
    HomeMomentQuantizationAuditor,
    HomeMomentQuantizationDiagnostics,
    HomeMomentQuantizationSpec,
    quantize_dequantize_home_moments,
)
from .reference import (
    equilibrium_convective_populations,
    extract_moments,
    periodic_home_convective_density_momentum_increment,
    periodic_home_convective_momentum_increment,
    reconstruct_populations,
)
from .rigid_geometry import HomeLbmRigidGeometry, RigidGeometryUpdateDiagnostics
from .rigid_coupling import HomeLbmRigidCoupling, HomeLbmRigidStepDiagnostics
from .rigid_interface import HomeLbmRigidInterface
from .scaling import LatticeScaling
from .solver import HomeLbmSolver
from .state import HomeLbmState
from .transitions import CellTransitionDiagnostics, ConservativeCellRemapper
from .vof import (
    FslActiveTransitionDiagnostics,
    FslActiveTransitionReference,
    FslActiveTransitionRemapper,
    FslBoundaryCoefficients,
    FslFaceCourantDiagnostics,
    FslFaceCourantReference,
    FslBulkStrainDiagnostics,
    FslBulkStrainReference,
    FslNormalStrainReference,
    FslStressClosureDiagnostics,
    FslStreamResult,
    CourantProjectionReference,
    GeometricPlicTopologyDiagnostics,
    GeometricPlicTopologyReference,
    HomeFreeCellFlag,
    HomeFreeCourantProjectionDiagnostics,
    HomeFreeCourantProjectionResult,
    HomeFreeCourantProjector,
    HomeFreeDomain,
    HomeFreeDomainState,
    HomeFreeLegacyDomain,
    HomeFreeBackend,
    HomeFreeFslResearchStepDiagnostics,
    HomeFreeFslResearchStepper,
    HomeFreeFslFaceCourantBuilder,
    HomeFreeFslBulkStrainBuilder,
    HomeFreeFslStressClosure,
    HomeFreeGeometricAxisAdvector,
    HomeFreeGeometricDomain,
    HomeFreeGeometricQueueDiagnostics,
    HomeFreeGeometricQueueMaterializer,
    HomeFreeGeometricTransport,
    HomeFreeGeometricTransportResult,
    HomeFreeGeometricTopologyResolver,
    HomeFreeGeometryDiagnostics,
    HomeFreeInterfaceGeometry,
    HomeFreeMassAdvector,
    HomeFreeOmResearchStepDiagnostics,
    HomeFreeOmResearchStepper,
    HomeFreeOmTransactionHistory,
    HomeFreeRigidInterface,
    HomeFreeRigidDynamicStepDiagnostics,
    HomeFreeRigidCoupling,
    HomeFreeRigidLoadDiagnostics,
    HomeFreeRigidPrepareDiagnostics,
    HomeFreeRigidPhaseRemap,
    HomeFreeRigidStaticStepDiagnostics,
    HomeFreeRigidStepDiagnostics,
    HomeFreeRigidTransitionDiagnostics,
    HomeFreeRigidTransitionRemapper,
    HomeFreeState,
    HomeFreeStateDiagnostics,
    OnlyMissingBoundaryResidual,
    HomeFreeSurfaceTension,
    HomeFreeSurfaceTensionDiagnostics,
    HomeFreeTopologyUpdater,
    PlicCurvatureFit,
    PlicAxisAdvectionDiagnostics,
    PlicAxisAdvectionResult,
    PlicLinkIntersection,
    PlicFslLinkCoverage,
    PlicLinkPlaneOwner,
    PlicPullLinkCoverage,
    PlicPullLinkStatus,
    advect_internal_link_mass_momentum,
    advect_plic_axis,
    interface_home_convective_density_momentum_increment,
    advect_mass_momentum_remap,
    discrete_capillary_pressure_link_momentum,
    fsl_boundary_coefficients,
    fsl_face_courant,
    fsl_normal_strain_targets,
    fsl_boundary_population,
    fsl_extrapolated_boundary_velocity,
    fsl_extrapolated_boundary_strain,
    fsl_stream_moments,
    fit_plic_curvature,
    classify_moving_solid_phases,
    contact_angle_interface_normal,
    gas_pressure_boundary_populations,
    home_internal_link_momentum,
    normalize_advected_mass_momentum_and_excess,
    normalize_mass_momentum_and_excess,
    only_missing_boundary_residual,
    reference_pressure_link_momentum,
    remap_fsl_active_moments,
    reconstruct_fsl_bulk_strain,
    plic_capillary_pressure_momentum,
    plane_interface_area,
    plane_volume_fraction,
    project_face_courant_reference,
    plic_plane_offset,
    plic_swept_slab_volume,
    plic_pull_link_intersection,
    plic_pull_link_coverage,
    plic_fsl_link_coverage,
    represented_liquid_momentum,
    resolve_geometric_plic_topology,
    youngs_interface_normal,
    create_home_free_domain,
)
from .wrench import FluidWrenchBuffer

__all__ = [
    "D3Q27_DIRECTIONS",
    "D3Q27_OPPOSITE",
    "D3Q27_WEIGHTS",
    "CutLinkBuffer",
    "CellTransitionDiagnostics",
    "ConservativeCellRemapper",
    "FluidWrenchBuffer",
    "MOMENT_COUNT",
    "HomeLbmDomain",
    "HomeLbmDiagnostics",
    "HomeLbmModel",
    "HomeMomentQuantizationAuditor",
    "HomeMomentQuantizationDiagnostics",
    "HomeMomentQuantizationSpec",
    "SphereWallLubrication",
    "SphereWallLubricationConfig",
    "HomeLbmRigidGeometry",
    "HomeLbmRigidCoupling",
    "HomeLbmRigidStepDiagnostics",
    "RigidGeometryUpdateDiagnostics",
    "HomeLbmRigidInterface",
    "HomeLbmSolver",
    "HomeLbmState",
    "HomeFreeCellFlag",
    "HomeFreeCourantProjectionDiagnostics",
    "HomeFreeCourantProjectionResult",
    "HomeFreeCourantProjector",
    "HomeFreeDomain",
    "HomeFreeDomainState",
    "HomeFreeLegacyDomain",
    "HomeFreeBackend",
    "HomeFreeFslResearchStepDiagnostics",
    "HomeFreeFslResearchStepper",
    "HomeFreeFslFaceCourantBuilder",
    "HomeFreeFslBulkStrainBuilder",
    "HomeFreeFslStressClosure",
    "HomeFreeGeometricAxisAdvector",
    "HomeFreeGeometricDomain",
    "HomeFreeGeometricQueueDiagnostics",
    "HomeFreeGeometricQueueMaterializer",
    "HomeFreeGeometricTransport",
    "HomeFreeGeometricTransportResult",
    "HomeFreeGeometricTopologyResolver",
    "HomeFreeGeometryDiagnostics",
    "HomeFreeInterfaceGeometry",
    "HomeFreeMassAdvector",
    "HomeFreeOmResearchStepDiagnostics",
    "HomeFreeOmResearchStepper",
    "HomeFreeOmTransactionHistory",
    "HomeFreeRigidInterface",
    "HomeFreeRigidDynamicStepDiagnostics",
    "HomeFreeRigidCoupling",
    "HomeFreeRigidLoadDiagnostics",
    "HomeFreeRigidPrepareDiagnostics",
    "HomeFreeRigidPhaseRemap",
    "HomeFreeRigidStaticStepDiagnostics",
    "HomeFreeRigidStepDiagnostics",
    "HomeFreeRigidTransitionDiagnostics",
    "HomeFreeRigidTransitionRemapper",
    "HomeFreeState",
    "HomeFreeStateDiagnostics",
    "FslActiveTransitionDiagnostics",
    "FslActiveTransitionReference",
    "FslActiveTransitionRemapper",
    "FslBoundaryCoefficients",
    "FslFaceCourantDiagnostics",
    "FslFaceCourantReference",
    "FslBulkStrainDiagnostics",
    "FslBulkStrainReference",
    "FslNormalStrainReference",
    "FslStressClosureDiagnostics",
    "FslStreamResult",
    "CourantProjectionReference",
    "GeometricPlicTopologyDiagnostics",
    "GeometricPlicTopologyReference",
    "OnlyMissingBoundaryResidual",
    "HomeFreeSurfaceTension",
    "HomeFreeSurfaceTensionDiagnostics",
    "HomeFreeTopologyUpdater",
    "PlicCurvatureFit",
    "PlicAxisAdvectionDiagnostics",
    "PlicAxisAdvectionResult",
    "PlicLinkIntersection",
    "PlicFslLinkCoverage",
    "PlicLinkPlaneOwner",
    "PlicPullLinkCoverage",
    "PlicPullLinkStatus",
    "advect_internal_link_mass_momentum",
    "advect_plic_axis",
    "interface_home_convective_density_momentum_increment",
    "advect_mass_momentum_remap",
    "discrete_capillary_pressure_link_momentum",
    "fsl_boundary_coefficients",
    "fsl_face_courant",
    "fsl_normal_strain_targets",
    "fsl_boundary_population",
    "fsl_extrapolated_boundary_velocity",
    "fsl_extrapolated_boundary_strain",
    "fsl_stream_moments",
    "gas_pressure_boundary_populations",
    "home_internal_link_momentum",
    "normalize_advected_mass_momentum_and_excess",
    "normalize_mass_momentum_and_excess",
    "only_missing_boundary_residual",
    "reference_pressure_link_momentum",
    "remap_fsl_active_moments",
    "reconstruct_fsl_bulk_strain",
    "plic_capillary_pressure_momentum",
    "plane_interface_area",
    "classify_moving_solid_phases",
    "contact_angle_interface_normal",
    "fit_plic_curvature",
    "plane_volume_fraction",
    "project_face_courant_reference",
    "plic_plane_offset",
    "plic_swept_slab_volume",
    "plic_pull_link_intersection",
    "plic_pull_link_coverage",
    "plic_fsl_link_coverage",
    "represented_liquid_momentum",
    "resolve_geometric_plic_topology",
    "LatticeScaling",
    "RigidMotionPredictor",
    "collide_central_moments",
    "equilibrium_convective_populations",
    "extract_moments",
    "linear_bouzidi_reflection",
    "periodic_home_convective_density_momentum_increment",
    "periodic_home_convective_momentum_increment",
    "reconstruct_populations",
    "youngs_interface_normal",
    "quantize_dequantize_home_moments",
    "create_home_free_domain",
]
