# SPDX-FileCopyrightText: Copyright (c) 2026 WanPhys Developers
# SPDX-License-Identifier: Apache-2.0

"""NumPy reference for the HOME third-order Hermite projection.

This implementation is an executable specification used to validate Warp
kernels.  It is not part of the simulation hot path.
"""

from __future__ import annotations

import numpy as np

from .constants import CS2, CS4, CS6, D3Q27_DIRECTIONS, D3Q27_WEIGHTS, MOMENT_COUNT


def _validate_moments(moments: np.ndarray) -> np.ndarray:
    values = np.asarray(moments, dtype=np.float64)
    if values.shape[-1] != MOMENT_COUNT:
        raise ValueError(f"expected last dimension of size {MOMENT_COUNT}, got {values.shape}")
    if np.any(values[..., 0] <= 0.0):
        raise ValueError("HOME reconstruction requires strictly positive density")
    return values


def reconstruct_populations(moments: np.ndarray) -> np.ndarray:
    """Reconstruct D3Q27 populations with paper Eq. (17).

    Input components are ``rho, rho*u, rho*S``.  The third-order coefficient
    uses the Malaspinas recurrence in symmetric tensor form:

    ``a3_abc = a2_ab*u_c + a2_ac*u_b + a2_bc*u_a - 2*rho*u_a*u_b*u_c``.
    """

    values = _validate_moments(moments)
    rho = values[..., 0]
    momentum = values[..., 1:4]
    velocity = momentum / rho[..., None]

    a2 = np.empty(values.shape[:-1] + (3, 3), dtype=np.float64)
    a2[..., 0, 0] = values[..., 4]
    a2[..., 1, 1] = values[..., 5]
    a2[..., 2, 2] = values[..., 6]
    a2[..., 0, 1] = a2[..., 1, 0] = values[..., 7]
    a2[..., 0, 2] = a2[..., 2, 0] = values[..., 8]
    a2[..., 1, 2] = a2[..., 2, 1] = values[..., 9]

    a3 = (
        np.einsum("...ab,...c->...abc", a2, velocity)
        + np.einsum("...ac,...b->...abc", a2, velocity)
        + np.einsum("...bc,...a->...abc", a2, velocity)
        - 2.0 * rho[..., None, None, None] * np.einsum("...a,...b,...c->...abc", velocity, velocity, velocity)
    )

    identity = np.eye(3, dtype=np.float64)
    populations = np.empty(values.shape[:-1] + (27,), dtype=np.float64)
    for direction, (c, weight) in enumerate(zip(D3Q27_DIRECTIONS, D3Q27_WEIGHTS, strict=True)):
        h2 = np.outer(c, c) - CS2 * identity
        h3 = np.einsum("a,b,c->abc", c, c, c) - CS2 * (
            np.einsum("a,bc->abc", c, identity)
            + np.einsum("b,ac->abc", c, identity)
            + np.einsum("c,ab->abc", c, identity)
        )
        populations[..., direction] = weight * (
            rho
            + np.einsum("...a,a->...", momentum, c) / CS2
            + np.einsum("...ab,ab->...", a2, h2) / (2.0 * CS4)
            + np.einsum("...abc,abc->...", a3, h3) / (6.0 * CS6)
        )
    return populations


def equilibrium_convective_populations(moments: np.ndarray) -> np.ndarray:
    """Return the nonlinear equilibrium part of the HOME reconstruction.

    This is the Hermite contribution generated by ``a2_eq = rho*u*u`` and
    its third-order recurrence ``a3_eq = rho*u*u*u``.  It has zero zeroth
    and first local moments, while its second moment is exactly ``rho*u*u``.
    Pressure, non-equilibrium stress, forcing, and boundary populations are
    deliberately absent.
    """

    values = _validate_moments(moments)
    rho = values[..., 0]
    velocity = values[..., 1:4] / rho[..., None]
    directions = D3Q27_DIRECTIONS.astype(np.float64)
    cu = np.einsum("...a,qa->...q", velocity, directions)
    speed_squared = np.einsum("...a,...a->...", velocity, velocity)
    h2 = cu * cu - CS2 * speed_squared[..., None]
    h3 = cu * cu * cu - 3.0 * CS2 * cu * speed_squared[..., None]
    return (
        D3Q27_WEIGHTS
        * rho[..., None]
        * (h2 / (2.0 * CS4) + h3 / (6.0 * CS6))
    )


def periodic_home_convective_density_momentum_increment(
    moments: np.ndarray,
) -> np.ndarray:
    """Extract HOME's nonlinear equilibrium density/momentum stream increment.

    The result is the exact pull-stream contribution of
    :func:`equilibrium_convective_populations`.  Requiring a periodic domain
    keeps wall, gas-pressure, and cut-link impulses outside this ledger.
    """

    values = _validate_moments(moments)
    if values.ndim != 4:
        raise ValueError("periodic HOME convection requires grid shape + (10,)")
    convective = equilibrium_convective_populations(values)
    increment = np.zeros(values.shape[:-1] + (4,), dtype=np.float64)
    axes = (0, 1, 2)
    for direction, c in enumerate(D3Q27_DIRECTIONS.astype(np.int32)):
        incoming = np.roll(
            convective[..., direction],
            shift=tuple(int(component) for component in c),
            axis=axes,
        )
        increment[..., 0] += incoming
        increment[..., 1:4] += incoming[..., None] * c
    return increment


def periodic_home_convective_momentum_increment(
    moments: np.ndarray,
) -> np.ndarray:
    """Return the momentum part of the periodic HOME convection ledger."""

    return periodic_home_convective_density_momentum_increment(moments)[..., 1:4]


def extract_moments(populations: np.ndarray) -> np.ndarray:
    """Project D3Q27 populations to the ten persistent HOME moments."""

    values = np.asarray(populations, dtype=np.float64)
    if values.shape[-1] != 27:
        raise ValueError(f"expected last dimension of size 27, got {values.shape}")

    rho = values.sum(axis=-1)
    momentum = np.einsum("...q,qa->...a", values, D3Q27_DIRECTIONS)
    raw_second = np.einsum("...q,qa,qb->...ab", values, D3Q27_DIRECTIONS, D3Q27_DIRECTIONS)
    a2 = raw_second - CS2 * rho[..., None, None] * np.eye(3, dtype=np.float64)

    moments = np.empty(values.shape[:-1] + (MOMENT_COUNT,), dtype=np.float64)
    moments[..., 0] = rho
    moments[..., 1:4] = momentum
    moments[..., 4] = a2[..., 0, 0]
    moments[..., 5] = a2[..., 1, 1]
    moments[..., 6] = a2[..., 2, 2]
    moments[..., 7] = a2[..., 0, 1]
    moments[..., 8] = a2[..., 0, 2]
    moments[..., 9] = a2[..., 1, 2]
    return moments
